#!/bin/sh

# simple topology checker (only checks xsd validation)

echo " --------------- "

# xmlstarlet 1.3.0 will print the first two urls on the same line, get 1.5.0

for topourl in `xmlstarlet select -t -v "/nml:Topology/nml:Topology/@nsi:isReference" master.xml`; do

    echo $topourl
    curl $topourl -fsS | xmllint -noout --schema schemas/nsi-ext.xsd -
    echo " --------------- "

done



